server:
  port: 11001
spring:
  application:
    name: ProvideService
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.137.128:8848
        group: provide
management:
  endpoint:
    web:
      exposure:
        include: '*'


